2024-12-27 19:04:03,172 | INFO | "test_challenge" выполнен успешно
2024-12-27 19:04:03,172 | WARNING | Неверный тип данных для объекта Runner
Имя может быть только строкой, передано int
2024-12-27 19:04:03,173 | WARNING | Traceback (most recent call last):
  File "C:\Users\gal91\FRFR\urban\1\tests_12_4.py", line 65, in test_run
    runner = Runner(2)
             ^^^^^^^^^
  File "C:\Users\gal91\FRFR\urban\1\tests_12_4.py", line 12, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int

2024-12-27 19:04:03,173 | WARNING | Неверная скорость для Runner
Скорость не может быть отрицательной, сейчас -5
2024-12-27 19:04:03,176 | WARNING | Traceback (most recent call last):
  File "C:\Users\gal91\FRFR\urban\1\tests_12_4.py", line 55, in test_walk
    runner = Runner("Вася", -5)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\gal91\FRFR\urban\1\tests_12_4.py", line 17, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5

